//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int id { get; set; }
        public string name { get; set; }
        public string kind { get; set; }
        public string identityNumber { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> rentedDay { get; set; }
        public string roomName { get; set; }
        public Nullable<int> ordinalNumber { get; set; }
    
        public virtual RoomCategory RoomCategory { get; set; }
    }
}
