//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        public int id { get; set; }
        public int nRoomKind { get; set; }
        public string roomKindPrice { get; set; }
        public int nCustomerKind { get; set; }
        public string customerKindCoefficient { get; set; }
        public int maximumCustomer { get; set; }
        public double surchargeRatio { get; set; }
        public int surchargeBeginning { get; set; }
    }
}
